gText_Birch_Welcome::
	.string "Hello, there!\n"
	.string "Glad to meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p"
	.string "For some people, POKéMON are pets.\n"
	.string "Others use them for battling.\p"
	.string "As for myself…\p"
	.string "I study POKéMON as a profession.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "Right…\n"
	.string "So your name is {PLAYER}{KUN}.$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\n"
	.string "You're {PLAYER}{KUN}, my neighbor.\p"
	.string "You've been my grandson Blue's rival\n"
	.string "since you both were babies.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}!\p"
	.string "Your very own POKéMON legend is\n"
	.string "about to unfold!\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "$"
